version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017

  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      /mongo-seed/import.sh
    
  memories_server:
    build: ./server
    volumes: 
      - ./server:/index
    command: npm start
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      CONNECTION_URL: mongodb://localhost:27017/postmessages
    
  memories_client:
    build: ./client
    volumes:
      - ./client:/index
    ports:
      - 3000:3000